# Main entrypoint of the workflow. 

configfile: "config/config.yml"
#container: config["container"]

include: "rules/common.smk"
include: "rules/aatrnaseq.smk"

rule all:
	input:
		pipeline_outputs(),