# Main entrypoint of the workflow. 


configfile: "config/config.yml"

SNAKEFILE_DIR = os.path.dirname(workflow.snakefile)
PIPELINE_DIR = os.path.dirname(SNAKEFILE_DIR)

include: "rules/common.smk"
include: "rules/aatrnaseq.smk"

report_metadata()

rule all:
	input:
		pipeline_outputs(),