name: aa-trna-seq-pipeline

channels:
  - conda-forge
  - bioconda
  - hcc

dependencies:
  - pysam
  - numpy
  - pandas
  - samtools
  - bwa
  - deeptools
  - snakemake >= 8.0
  - snakefmt
  - gitpython
  - pip
  - dorado >= 0.7.2
  - f5c
  - squigualiser
  - pip:
    - pod5
    - ont-remora >= 3.2
    - snakemake-executor-plugin-lsf
    - snakemake-executor-plugin-slurm
    - snakemake-executor-plugin-cluster-generic 
    - blue-crab
