executor: lsf
jobs: 100

# N.B. GB values should be passed to mem_mb
default-resources:
  - 'mem_mb=8'
  - 'lsf_queue=rna'
  - 'lsf_project=aatrnaseq'
  - 'lsf_extra=""'

resources:
  - ngpu=8

# set rule specific requirements
set-resources:
  - rebasecall:lsf_queue="gpu"
  - rebasecall:lsf_extra="-gpu num=1:j_exclusive=yes:mode=exclusive_process"
  - rebasecall:ngpu=1
  - rebasecall:mem_mb=24
  - classify_aa:lsf_queue="gpu"
  - classify_aa:lsf_extra="-gpu num=1:j_exclusive=yes:mode=exclusive_process"
  - classify_aa:ngpu=1
  - classify_aa:mem_mb=48
  - classify_charging:mem_mb=24
  - classify_charging_leech:lsf_queue="gpu"
  - classify_charging_leech:lsf_extra="-gpu num=1:j_exclusive=yes:mode=exclusive_process"
  - classify_charging_leech:ngpu=1
  - classify_charging_leech:mem_mb=24
  - remora_signal_stats:mem_mb=24
  - inject_ubam_tags:mem_mb=16
  - bwa_align:mem_mb=24
  - modkit_extract_calls:mem_mb=96
  - modkit_extract_full:mem_mb=48
  - warpdemux:mem_mb=32
  - parse_warpdemux:mem_mb=8
  - escpod_demux:mem_mb=32
  - parse_escpod_demux:mem_mb=8
  - extract_escpod_sample_reads:mem_mb=8
  - collect_escpod_pod5:mem_mb=16

printshellcmds: True
show-failed-logs: True
latency-wait: 60
