# base config for aa-tRNA-seq pipeline
# this is included in the main Snakefile

# either a path to a basecalling model to use with dorado or a model selection name to specify model to download and use
base_calling_model: "resources/models/rna004_130bps_sup@v5.0.0"

# either FAST5 or POD5, if FAST5 then these files will be converted to pod5 before rebasecalling
input_format: "POD5"

# path to fasta file to use for bwa alignment.
# a BWA index will be built if it does not exist for this fasta file
fasta: "resources/ref/sacCer3-mature-tRNAs-dual-adapt-v2.fa"

# If a kmer table if provided then the pipeline will use get_signal_metrics.py to extract metrics using remora
# from: https://github.com/nanoporetech/kmer_models/tree/master/rna004
remora_kmer_table: "resources/kmers/9mer_levels_v1.txt"

# read classification model - remora trained model to classify charged vs uncharged reads
remora_cca_classifier: "resources/models/cca_classifier.pt"

# additional options for particular commands
opts:
    # additional options for dorado basecalling e.g
    dorado: " --emit-moves "

    # additional options for bwa alignment
    # based on Novoa lab optimising bwa for tRNA alignment
    # the -h 20 option is used to increase the number of secondary alignments reported in the XA tag
    bwa: " -W 13 -k 6 -T 20 -x ont2d"

    # requires positive strand alignment
    # requires at least 1 5' adapter base
    # requires 1 3' adapter base in the discriminating adapter region between charged and uncharged (v2 adapters).
    bam_filter: "-5 24 -3 23 -s"

    #requires positive strand alignment and excludes non-primary alignments
    coverage: "--filterRNAstrand 'reverse' --samFlagExclude 256"

    # pass additional options to get_signal_metrics.py script which uses Remora to calculate metrics
    remora: ""
