# new config for running uncharged nanopore tRNA-seq libraries (to be edited)
# paths to basecalling models below (these will need to be added to resources dir unless we can point to Dorado install instead)
base_calling_models:
  RNA002:
    tRNA:
      - "resources/models/rna002_70bps_fast@v3"
      - "resources/models/rna002_70bps_hac@v3"
    aa-tRNA: "resources/models/rna002_70bps_hac@v3"
  RNA004:
    tRNA:
      - "resources/models/rna004_130bps_fast@v5.1.0"
      - "resources/models/rna004_130bps_hac@v5.1.0"
      - "resources/models/rna004_130bps_sup@v5.1.0"
    aa-tRNA: "resources/models/rna004_130bps_sup@v5.1.0"

# either FAST5 or POD5, if FAST5 then these files will be converted to pod5 before rebasecalling
input_format: "POD5"

output_directory: "results/"

# paths to fasta files to use for bwa alignment for uncharged tRNA sequencing
# will built a BWA index for each if it doesn't exist
references:
    scerevisiae: "resources/ref/uncharged/sacCer-mito-and-nuclear-tRNAs.fa"
    hsapiens: "resources/ref/uncharged/hg38-mature-tRNAs.fa"
    drerio: "resources/ref/uncharged/danRer11-mature-tRNAs.fa"
    tthermophila: "resources/ref/uncharged/tthermophila-numbered-mature-tRNAs.fa"
    dmelanogaster: "resources/ref/uncharged/dm6-mature-tRNAs.fa"
    ecoli: "resources/ref/uncharged/ecoliK12MG1655-mature-tRNAs.fa"

# If a kmer table if provided then the pipeline will use get_signal_metrics.py to extract metrics using remora
# from: https://github.com/nanoporetech/kmer_models/tree/master/rna004
remora_kmer_table: "resources/kmers/9mer_levels_v1.txt"

# read classification model - remora trained model to classify charged vs uncharged reads
remora_cca_classifier: "resources/models/cca_classifier.pt"

# additional options for particular commands
opts:
    # additional options for dorado basecalling e.g
    dorado: " --emit-moves "

    # additional options for bwa alignment
    # based on Novoa lab optimising bwa for tRNA alignment
    # the -h 20 option is used to increase the number of secondary alignments reported in the XA tag
    bwa: " -W 13 -k 6 -T 20 -x ont2d"

    # requires positive strand alignment
    # requires at least 1 5' adapter base
    # requires 1 3' adapter base in the discriminating adapter region between charged and uncharged (v2 adapters).
    bam_filter: "-5 24 -3 23 -s"

    #requires positive strand alignment and excludes non-primary alignments
    coverage: "--filterRNAstrand 'reverse' --samFlagExclude 256"

    # pass additional options to get_signal_metrics.py script which uses Remora to calculate metrics
    remora: ""
